### ISSUE TITLE
pushd not found

### ISSUE THREAD

**Issue by xXValiXx** [StrayRobots/issues#2]
**Describe the bug**
While executing install script i get the error:  `sh: 79: pushd: not found`

**To Reproduce**
1. Install debian
2. add user to sudoers and docker group
3. install docker
4. execute install script
5. see error

**Expected behavior**
Thought the script would install the stray app

**Screenshots**
![grafik](https://user-images.githubusercontent.com/47116168/133037156-1649ebf9-725b-471d-aff2-bb98b7fee993.png)

**Desktop (please complete the following information):**
 - OS: [Debian]
 - Version [11]

**Additional context**

**Comment by hietalajulius** [comment]
Hi @xXValiXx, huge apologies for the issue!

Can you try installing with `curl --proto '=https' --tlsv1.2 -sSf https://stray-builds.ams3.digitaloceanspaces.com/cli/install.sh | bash` instead? We also just pushed a new linux build, hopefully that fixes the issue here https://github.com/StrayRobots/issues/issues/1 too.
